In [ ]:
# -*- coding: utf-8 -*-
"""
Created on 2021

@author: Administrator
"""

'\nCreated on 2021\n\n@author: Administrator\n'

In [ ]:
#%%

# =============================================================================
# =============================================================================
# # 문제 01 유형(DataSet_01.csv 이용)
#
# 구분자 : comma(“,”), 4,572 Rows, 5 Columns, UTF-8 인코딩
#
# 글로벌 전자제품 제조회사에서 효과적인 마케팅 방법을 찾기
# 위해서 채널별 마케팅 예산과 매출금액과의 관계를 분석하고자
# 한다.
# 컬 럼 / 정 의  /   Type
# TV   /     TV 마케팅 예산 (억원)  /   Double
# Radio / 라디오 마케팅 예산 (억원)  /   Double
# Social_Media / 소셜미디어 마케팅 예산 (억원)  / Double
# Influencer / 인플루언서 마케팅
# (인플루언서의 영향력 크기에 따라 Mega / Macro / Micro /
# Nano) / String

# SALES / 매출액 / Double
# =============================================================================
# =============================================================================

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('Dataset_01.csv')
df

        TV      Radio  Social_Media Influencer       Sales
0     16.0   6.566231      2.907983       Mega   54.732757
1     13.0   9.237765      2.409567       Mega   46.677897
2     41.0  15.886446      2.913410       Mega  150.177829
3     83.0  30.020028      6.922304       Mega  298.246340
4     15.0   8.437408      1.405998      Micro   56.594181
...    ...        ...           ...        ...         ...
4567  26.0   4.472360      0.717090      Micro   94.685866
4568  71.0  20.610685      6.545573       Nano  249.101915
4569  44.0  19.800072      5.096192      Micro  163.631457
4570  71.0  17.534640      1.940873      Macro  253.610411
4571  42.0  15.966688      5.046548      Micro  148.202414

[4572 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TV            4562 non-null   float64
 1   Radio         4568 non-null   float64
 2   Social_Media  4566 non-null   float64
 3   Influencer    4572 non-null   object
 4   Sales         4566 non-null   float64
dtypes: float64(4), object(1)
memory usage: 178.7+ KB

In [ ]:
df.columns

Index(['TV', 'Radio', 'Social_Media', 'Influencer', 'Sales'], dtype='object')

In [ ]:
#%%

# =============================================================================
# 1. 데이터 세트 내에 총 결측값의 개수는 몇 개인가? (답안 예시) 23
# =============================================================================

#df.info()
#df.columns

# 결측지가 포함된 셀의 수
# df.isna().sum() # 이렇게 치면 각 열마다 결측지의 개수가 나옴
df.isna().sum().sum() # 문제의 답은 요거임

# 결측지가 포함된 행 추출
#df[df.isna().any(axis=1)]

tmp_df = df.copy()
tmp_df['TV'] = tmp_df['TV'].fillna(70)
tmp_df['TV'][df['TV'].isna()]

13     70.0
26     70.0
46     70.0
75     70.0
99     70.0
119    70.0
141    70.0
163    70.0
183    70.0
210    70.0
Name: TV, dtype: float64

In [ ]:
#%%

# =============================================================================
# 2. TV, Radio, Social Media 등 세 가지 다른 마케팅 채널의 예산과 매출액과의 상관분석을
# 통하여 각 채널이 매출에 어느 정도 연관이 있는지 알아보고자 한다.
# - 매출액과 가장 강한 상관관계를 가지고 있는 채널의 상관계수를 소수점 5번째
# 자리에서 반올림하여 소수점 넷째 자리까지 기술하시오. (답안 예시) 0.1234
# =============================================================================

q2=df.corr().drop('Sales')['Sales'].abs() # Y변수 열을 추출
round(q2.max(), 4)

0.9995

In [ ]:
# X 변수 리스트를 추출
q2.max() # 최대값
q2.argmax() # 최대값이 있는 위치 번호
q2.idxmax() # 최대값이 있는 인덱스 번호
q2.nlargest(2) # 상위 2개의 변수명, 값
q2[q2 >= 0.6].index

q2.min()
q2.argmin()
q2.idxmin()
q2.nsmallest(2)

Social_Media    0.528906
Radio           0.869105
Name: Sales, dtype: float64

In [ ]:
np.floor(1234.5678*100)/100 #내림
np.ceil(1234.5678*100)/100 #올림

import scipy.stats as st

In [ ]:
tmp = df.dropna()
#st.pearsonr(df['TV'], df['Sales']) 결측지 때문에 사용불가
st.pearsonr(tmp['TV'], tmp['Sales'])[0]

0.9994973659385121

In [ ]:
#%%

# =============================================================================
# 3. 매출액을 종속변수, TV, Radio, Social Media의 예산을 독립변수로 하여 회귀분석을
# 수행하였을 때, 세 개의 독립변수의 회귀계수를 큰 것에서부터 작은 것 순으로
# 기술하시오.
# - 분석 시 결측치가 포함된 행은 제거한 후 진행하며, 회귀계수는 소수점 넷째 자리
# 이하는 버리고 소수점 셋째 자리까지 기술하시오. (답안 예시) 0.123
# =============================================================================

In [ ]:
#%%

# =============================================================================
# =============================================================================
# # 문제 02 유형(DataSet_02.csv 이용)
# 구분자 : comma(“,”), 200 Rows, 6 Columns, UTF-8 인코딩

# 환자의 상태와 그에 따라 처방된 약에 대한 정보를 분석하고자한다
#
# 컬 럼 / 정 의  / Type
# Age  / 연령 / Integer
# Sex / 성별 / String
# BP / 혈압 레벨 / String
# Cholesterol / 콜레스테롤 레벨 /  String
# Na_to_k / 혈액 내 칼륨에 대비한 나트륨 비율 / Double
# Drug / Drug Type / String
# =============================================================================
# =============================================================================

import pandas as pd
import numpy as np

df1 = pd.read_csv('Dataset_02.csv')
df1

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [ ]:
# =============================================================================
# 1.해당 데이터에 대한 EDA를 수행하고, 여성으로 혈압이 High, Cholesterol이 Normal인
# 환자의 전체에 대비한 비율이 얼마인지 소수점 네 번째 자리에서 반올림하여 소수점 셋째
# 자리까지 기술하시오. (답안 예시) 0.123
# =============================================================================

df1.columns

var_list = ['Sex', 'BP', 'Cholesterol']
q1= df1[var_list].value_counts(normalize=True)

q1[('F', 'HIGH',  'NORMAL')] # 정답

tab1 = pd.crosstab(index=[df1['Sex'], df1['BP']],columns=df1['Cholesterol'], margins =True)
tab2 = pd.crosstab(index=[df1['Sex'], df1['BP']],columns=df1['Cholesterol'],
                   margins =True, normalize=True)

pd.concat([tab1, tab2], axis=1)

Cholesterol  HIGH  NORMAL  All   HIGH  NORMAL    All
Sex BP
F   HIGH       17      21   38  0.085   0.105  0.190
    LOW        14      14   28  0.070   0.070  0.140
    NORMAL     18      12   30  0.090   0.060  0.150
M   HIGH       18      21   39  0.090   0.105  0.195
    LOW        17      19   36  0.085   0.095  0.180
    NORMAL     19      10   29  0.095   0.050  0.145
All           103      97  200  0.515   0.485  1.000