In [10]:
inta = 1
intb = 2.1

# type(): 데이터 자료형 출력

print(type(inta))
print(type(intb))

print(inta+intb)

<class 'int'>
<class 'float'>
3.1

In [14]:
a=str
b=str

a = "123"
b = "python"

print(type(a),"\n",type(b))
print(a+b)

print(str(inta)+a)
print(inta+int(a))

<class 'str'>
 <class 'str'>
123python
1123
124

In [18]:
print(b[0]) #문자 출력시 []후 위치 값 입력
print(b[-1])
print(b[0:3])
print(b[:3])
print(b[-2:])

p
n
pyt
pyt
on

In [33]:
c=str
c="메이플 스토리를 하는 영석이"
print(c.count(" "))
c.find("",4)
print(c.split(" "))
len(c)

3
['메이플', '스토리를', '하는', '영석이']

15

In [32]:
c.replace("메이플 스토리","던전 앤 파이터")

'던전 앤 파이터를 하는 영석이'

In [35]:
lst1=[1,2,3,4,5]
lst2=[10,20,"멀티캠퍼스","python",[300,400,500]]

print(type(lst1))
print(type(lst2))

<class 'list'>
<class 'list'>

In [71]:
lori1=list
lori2=list
lori3=list

lori1=[1,2,3,4,5]
lori2=[10,20,"멀티캠퍼스","python",[300,400,500]]
lori3=['한글', '메이플스토리', '넥슨', '리니지' ]

print(type(lori1))
print(type(lori2))
print(lori2[2])
print(lori2[0:2])
print(lori2[-1])
print(lori2[-1][1]) #2차원 구조의 데이터 출력
print(lori2[4][2])

lori1.insert(0,6)
lori1

del lori3[3]

<class 'list'>
<class 'list'>
멀티캠퍼스
[10, 20]
[300, 400, 500]
400
500

In [43]:
lori2[2] = "multi campus"

In [44]:
print(lori2[2])

multi campus

In [53]:
lori2.append("메이플스토리")#리스트 끝에 값 추가
print(lori2)
print(lori1.sort())
print(lori3.sort())

lst1=[1,"홍길동","남"],[2,"이순신","남"]
print(lst1)
print(lst1[0][1])

[10, 20, '멀티캠퍼스', 'python', [300, 400, 500], '메이플스토리', '메이플스토리', '메이플스토리']
None
None
([1, '홍길동', '남'], [2, '이순신', '남'])
홍길동

In [60]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [61]:
import pandas as pd
df1=pd.DataFrame(lst1)
df1

   0    1  2
0  1  홍길동  남
1  2  이순신  남

In [63]:
dic1={"ID":1,"이름":"홍길동","성별":"남","국어 점수":80}
dic2={"ID":[1,2,3,4,5],"이름":["홍길동", "장길산", "임꺽정", "이순신", "송시열"],"성별":["남","여","남","여","남"],"국어 점수":[80,90,100,98,90]}
print(dic1.keys())
print(dic1.values())

print(dic2.values())
print(dic2.values())

dict_keys(['ID', '이름', '성별', '국어 점수'])
dict_values([1, '홍길동', '남', 80])
dict_values([[1, 2, 3, 4, 5], ['홍길동', '장길산', '임꺽정', '이순신', '송시열'], ['남', '여', '남', '여', '남'], [80, 90, 100, 98, 90]])
dict_values([[1, 2, 3, 4, 5], ['홍길동', '장길산', '임꺽정', '이순신', '송시열'], ['남', '여', '남', '여', '남'], [80, 90, 100, 98, 90]])

In [65]:
print(dic2["이름"])
df2=pd.DataFrame(dic2)
df2

['홍길동', '장길산', '임꺽정', '이순신', '송시열']

   ID   이름 성별  국어 점수
0   1  홍길동  남     80
1   2  장길산  여     90
2   3  임꺽정  남    100
3   4  이순신  여     98
4   5  송시열  남     90