In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_diabetes
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor

In [ ]:
# 당뇨병 데이터셋 불러오기
diabetes = load_diabetes()
df = pd.DataFrame(diabetes.data, columns = diabetes.feature_names)
df['target'] = diabetes.target
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019908,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068330,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005671,-0.045599,-0.034194,-0.032356,-0.002592,0.002864,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022692,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031991,-0.046641,135.0

## Linear Regression

In [ ]:
# Linear Regression
for feature in df.columns[:-1]:
  lr = LinearRegression()
  X = df[feature].values.reshape(-1,1) # 데이터프레임을 넘파이 배열구조로
  lr.fit(X, diabetes.target)
  lr.score(X, diabetes.target)

In [ ]:
# Linear Regression 학습
X_train, X_test, y_train, y_test = train_test_split(diabetes.data, diabetes.target,  random_state=2022)
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [ ]:
#평가
lr.score(X_test, y_test)

0.5205965595770596

In [ ]:
#  R-squared
lr.score(X_train, y_train)

0.5083943762319268

In [ ]:
# 계수(weight) / 절편(bias)
lr.coef_ , lr.intercept_

(array([  32.71740753, -239.04620592,  494.2624288 ,  340.0340352 ,
        -266.30112835,  112.12716999, -195.97735431,  -70.14692851,
         620.94232653,   81.21995399]), 154.33192759007935)

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error
pred_lr = lr.predict(X_test)
r2_lr = r2_score(y_test, pred_lr)
mse_lr = mean_squared_error(y_test, pred_lr)

 - SVR

In [ ]:
svr = SVR()
svr.fit(X_train, y_train)

pred_svr = svr.predict(X_test)
r2_svr = r2_score(y_test, pred_svr)
mse_svr = mean_squared_error(y_test, pred_svr)

 - Random Forest Regressor

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr.fit(X_train, y_train)
pred_rfr = rfr.predict(X_test)
r2_rfr = r2_score(y_test, pred_rfr)
mse_rfr = mean_squared_error(y_test, pred_rfr)

XGBoost

In [ ]:
from xgboost import XGBRegressor
xgr = XGBRegressor()
xgr.fit(X_train, y_train)
pred_xgr = xgr.predict(X_test)
r2_xgr = r2_score(y_test, pred_xgr)
mse_xgr = mean_squared_error(y_test, pred_xgr)

[08:58:38] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

각 회귀 모델 비교

y_test

In [ ]:
df1= pd.DataFrame({'y_test': y_test, 'LR':pred_lr, 'SVM':pred_svr, 'RF': pred_rfr, 'XGB': pred_xgr})
df1

     y_test          LR         SVM      RF         XGB
0      55.0   70.942192  131.828019  127.44  130.794708
1      96.0   61.700539  122.484391   76.38   64.896721
2     317.0  214.257161  149.701268  184.54  196.938461
3      40.0  143.063770  136.355134  136.50  110.763802
4     178.0  171.669798  149.710522  180.19  174.040146
..      ...         ...         ...     ...         ...
106   116.0  137.850193  146.040443  155.01  140.269440
107   108.0  113.118049  133.213494   97.03   82.492226
108    96.0   87.853214  124.469530   92.39   88.138115
109    91.0  174.764101  146.875665  150.82  161.499329
110   341.0  242.844795  152.565366  240.53  276.915924

[111 rows x 5 columns]

- R2 score

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error
df_r2= pd.DataFrame({'y_test': y_test, 'LR':r2_lr, 'SVM':r2_svr, 'RF': r2_rfr, 'XGB': r2_xgr})
df_r2

     y_test        LR       SVM        RF       XGB
0      55.0  0.520597  0.165656  0.447696  0.406042
1      96.0  0.520597  0.165656  0.447696  0.406042
2     317.0  0.520597  0.165656  0.447696  0.406042
3      40.0  0.520597  0.165656  0.447696  0.406042
4     178.0  0.520597  0.165656  0.447696  0.406042
..      ...       ...       ...       ...       ...
106   116.0  0.520597  0.165656  0.447696  0.406042
107   108.0  0.520597  0.165656  0.447696  0.406042
108    96.0  0.520597  0.165656  0.447696  0.406042
109    91.0  0.520597  0.165656  0.447696  0.406042
110   341.0  0.520597  0.165656  0.447696  0.406042

[111 rows x 5 columns]

Mean Squared Error

In [ ]:
df_mse= pd.DataFrame({'y_test': y_test, 'LR':mse_lr, 'SVM':mse_svr, 'RF': mse_rfr, 'XGB': mse_xgr})
df_mse

     y_test           LR         SVM           RF          XGB
0      55.0  2911.798212  5067.63684  3354.579853  3607.578881
1      96.0  2911.798212  5067.63684  3354.579853  3607.578881
2     317.0  2911.798212  5067.63684  3354.579853  3607.578881
3      40.0  2911.798212  5067.63684  3354.579853  3607.578881
4     178.0  2911.798212  5067.63684  3354.579853  3607.578881
..      ...          ...         ...          ...          ...
106   116.0  2911.798212  5067.63684  3354.579853  3607.578881
107   108.0  2911.798212  5067.63684  3354.579853  3607.578881
108    96.0  2911.798212  5067.63684  3354.579853  3607.578881
109    91.0  2911.798212  5067.63684  3354.579853  3607.578881
110   341.0  2911.798212  5067.63684  3354.579853  3607.578881

[111 rows x 5 columns]

In [ ]:
!jupyter nbconvert --to html "/content/drive/MyDrive/Multi/220427/다중회귀(당뇨).ipynb"

[NbConvertApp] Converting notebook /content/drive/MyDrive/Multi/220427/다중회귀(당뇨).ipynb to html
[NbConvertApp] Writing 313115 bytes to /content/drive/MyDrive/Multi/220427/다중회귀(당뇨).html

In [ ]:
!jupyter nbconvert --to html ""