### pandas 모듈
 - 2차원 구조가 기본이며 2차원 구조까지만 다룰 수 있음
 https://pandas.pydata.org/docs/index.html
- DataFrame 생성
 * pandas.DataFrame(시퀀스(리스트 / 딕셔너리),columns=[열이름],index =[인덱스값 지정])

In [ ]:
#리스트형 데이터를 이용한 DataFrame 구현
import pandas as pd

lst=[[1,95,48,88],[2,85,88,93],[3,80,70,60]]

# 데이터가 몇 개인지 알 수 없기 때문에 보통 리스트, 열 번호 정도만 정의 (인덱스 정의는 잘 안 함)
df1 = pd.DataFrame(lst,columns=["번호","국어","영어","수학"])
df1

   번호  국어  영어  수학
0   1  95  48  88
1   2  85  88  93
2   3  80  70  60

In [ ]:
#딕셔너리형 데이터를 이용한 DataFrame 구현 --> Json 형식써야될 때 많이 씀
import pandas as pd

dic={"번호":[1,2,3,4,5],"국어":[80,85,80,90,90],"영어":[70,75,80,85,90],"수학":[80,80,90,80,90]}

# 데이터가 몇 개인지 알 수 없기 때문에 보통 리스트, 열 번호 정도만 정의 (인덱스 정의는 잘 안 함)
df1 = pd.DataFrame(dic) # 딕셔너리형의 경우 열 번호를 따로 정의할 필요가 없음 (앞에서 이미 했으니까)
df1 #딕셔너리 형을 처리할 때는 데이터들이 무조건 다 들어가 있어야 된다.(하다 못해 null값이라도 넣어야 됨)

   번호  국어  영어  수학
0   1  80  70  80
1   2  85  75  80
2   3  80  80  90
3   4  90  85  80
4   5  90  90  90

In [ ]:
import pandas as pd

df1=pd.read_csv("/content/지역_위치별(주유소)_utf8.csv")
df1

In [ ]:
import pandas as pd

df2=pd.read_csv("/content/지역_위치별(주유소)_cp949.csv", encoding="cp949")
df2

In [ ]:
# 엑셀 파일 읽어오기 (주의: 구형 엑셀 버전은 작업이 조금 힘들 수 있다)

import pandas as pd

df1 = pd.read_excel("/content/남북한발전전력량.xlsx")
df1

In [ ]:
#Json 파일 읽어오기 (이거 특히 중요!!)

import pandas as pd

df1 = pd.read_json("/content/df_sample.json")
df1

In [ ]:
import pandas as pd

df1=pd.read_csv("/content/지역_위치별(주유소)_utf8.csv")
df1

#df1 전체 정보 확인하기
df1.info()

## 데이터.head(): DataFrame에서 상위 데이터 표시. 기본 5개,()숫자 입력 시 해당 데이터만큼 출력
df1.head()
df1.head(7)

#데이터.tail(): DataFrame에서 하위 데이터 표시 (위와 표시되는 개수 동일)
df1.tail()

In [ ]:
# 행/열 데이터 출력
# 열단위 데이터
df1['휘발유'] #1개 열의 값 출력
df1[['경유','휘발유']] # 2개 이상 열의 값 출력([]로 열이름을 묶어서 입력)
df1.columns # 열 이름 확인
display(df1[["상표", "셀프여부", "경유", "휘발유"]]) #display() 이용해서도 표시할 수 있다

In [ ]:
# 기술 통계
df2=df1[["상표", "셀프여부", "경유", "휘발유"]]
df2.describe() # 현재 있는 데이터는 모두 문자(object)로 텍스트 관련 통계만 보여줌

In [ ]:
## 행 기준 데이터 출력(loc[], iloc[])
# loc[]
df1.loc[0]   # index 열 기준
df1.loc[1:3]
df1.loc[1:3, ["휘발유", "경유"]]
df2=df1.loc[1:10, ["셀프여부","휘발유", "경유", "상표"]]
df2

        상표 셀프여부   휘발유    경유
1   현대오일뱅크    Y  1905  1800
2    GS칼텍스    Y  1907  1739
3    SK에너지    N  1940  1810
4    S-OIL    Y  1967  1798
5    SK에너지    Y  1979  1835
6    SK에너지    N  1979  1899
7   현대오일뱅크    Y  1979  1835
8    SK에너지    Y  1992  1887
9    SK에너지    Y  1995  1845
10   SK에너지    Y  1995  1895

In [ ]:
## iloc[]: 데이터의 행/열 인덱싱된 값을 기준으로 출력 (원래 있던 데이터의 위치값으로 계산)
df2.iloc[0]
df2.iloc[1:5]
df2.iloc[1:5, 0]
df2.iloc[1:5, 1:]
df2.iloc[1:5, [0,1,3]] # 열을 찾고 싶을 때 이름이 아니라 순번을 입력해야 한다

In [ ]:
# df2의 경유, 휘발유 값을 정수형 데이터로 변경
# df.dtypes: 각 필드(열)의 데이터 타입을 출력
lst=[]

for i in df2.index:
  lst.append(int(df2.loc[i,["휘발유"]])) # 휘발유 필드 값을 정수형 데이터로 변경
print(lst)
df2["휘발유"] = lst # 정수형 데이터로 변경한 df2의 휘발유 필드 값을 업데이트

df2.dtypes

[1905, 1907, 1940, 1967, 1979, 1979, 1979, 1992, 1995, 1995]

상표      object
셀프여부    object
휘발유      int64
경유      object
dtype: object

### df3 생성 후 경유(int), 휘발유 데이터(float)
- df.astype(데이터형,inplace=True), 모든 데이터를 입력한 형식으로 변경
- df = df.astype({"열이름":int, "필드명":float})

In [ ]:
# 위 코드의 for 구문을 한 줄쓰기로 변경
df3 = df1.loc[1:10,["셀프여부","휘발유", "경유", "상표"]]

df3 = df3.astype({"경유":int, "휘발유":float})
print(df3.dtypes)

In [ ]:
df3.describe()

In [ ]:
# for문을 이용하여 "휘발유","경유" 값을 int형으로 변경
# 변경 값이 "-"이면 해당 값은 0 값으로 변경
# df1에 적용 후 저장

lst2=[]
lst3=[]

df1 = df1.loc[1:10,["셀프여부","휘발유", "경유", "상표"]]

if df1["휘발유"] == "-":
  df1["휘발유"].replace("-",0,inplace=true)


for i in df1.index:
  lst2.append(int(df1.loc[i,["경유"]])
  lst3.append(float(df1.loc[i,["휘발유"])